### ISSUE TITLE
Blacklist PIN is 404

### ISSUE THREAD

**Issue by LouOtway** [ligos/MakeMeAPassword#6]
[The link](https://makemeapassword.ligos.net/content/data/PinBlacklist.txt) of blacklisted PINs comes up as 404.

**Comment by ligos** [comment]
The link to [blacklisted PINs on the FAQ page](https://makemeapassword.ligos.net/faq#pinblacklist) points to `https://makemeapassword.ligos.net/data/PinBlacklist.txt`. And seems to be working.

That's different to the link you added has an extra `/content`. 
It's been a while since the issue was created, so maybe I noticed it at some other time 🤷‍♂️

Murray
